[tool.poetry]
name = "repl_python3_Guessing-Game"
version = "0.1.0"
description = ""
authors = ["xqn <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
getch = "^1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
